name: CD INTERNAL DEV

on:
  push:
    branches: [ develop ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      internal_changed: ${{ steps.filter.outputs.internal }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          base: develop
          filters: |
            internal:
              - 'internal/**'

  build-internal:
    needs: detect-changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Grant execute permission for run-test-mysql.sh
        run: chmod +x run-test-mysql.sh
        working-directory: ./domain

      - name: Grant execute permission for run-test-redis.sh
        run: chmod +x run-test-redis.sh
        working-directory: ./common

      - name: Run test mysql script
        run: ./run-test-mysql.sh
        working-directory: ./domain

      - name: Run test redis script
        run: ./run-test-redis.sh
        working-directory: ./common

      - name: Test & Build internal only
        run: ./gradlew :internal:build

      - name: Sign in Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -f ./Dockerfile --platform linux/amd64 --no-cache -t samhap/kokomen-payment-internal:dev .
        working-directory: ./internal

      - name: Push the Docker Image to Dockerhub
        run: docker push samhap/kokomen-payment-internal:dev
        working-directory: ./internal

  deploy-internal:
    needs: build-internal
    runs-on: [ self-hosted, org, dev, new ]
    steps:
      - name: Stop existing container
        run: sudo docker rm -f kokomen-payment-dev-internal || true

      - name: Remove old INTERNAL Docker image
        run: |
          if sudo docker images samhap/kokomen-payment-internal:dev -q | grep -q .; then
            sudo docker rmi -f samhap/kokomen-payment-internal:dev || true
          fi

      - name: pull docker compose yaml files
        working-directory: /home/ubuntu
        run: |
          [ -d kokomen-payment ] || git clone --filter=blob:none --no-checkout https://github.com/samhap-soft/kokomen-payment.git
          cd kokomen-payment
          git sparse-checkout init --cone
          git fetch origin develop
          git checkout develop
          git sparse-checkout set docker/dev
          git pull origin develop

      - name: Docker Image pull
        run: sudo docker pull samhap/kokomen-payment-internal:dev

      - name: Docker run
        working-directory: /home/ubuntu
        env:
          MYSQL_ROOT_PASSWORD_DEV: ${{ secrets.MYSQL_ROOT_PASSWORD_DEV }}
          SPRING_DATASOURCE_USERNAME_DEV: ${{ secrets.SPRING_DATASOURCE_USERNAME_DEV }}
          SPRING_DATASOURCE_PASSWORD_DEV: ${{ secrets.SPRING_DATASOURCE_PASSWORD_DEV }}
        run: |
          export HOSTNAME=$(hostname)
          cd kokomen-payment/docker/dev
          sudo -E docker compose -f docker-compose-dev.yml up -d kokomen-payment-dev-internal
