name: CI INTERNAL TEST

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      internal_changed: ${{ steps.filter.outputs.internal }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            internal:
              - 'internal/**'

  build:
    needs: detect-changes
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Grant execute permission for run-test-mysql.sh
        run: chmod +x run-test-mysql.sh
        working-directory: ./domain

      - name: Grant execute permission for run-test-redis.sh
        run: chmod +x run-test-redis.sh
        working-directory: ./common

      - name: Run test mysql script
        run: ./run-test-mysql.sh
        working-directory: ./domain

      - name: Run test redis script
        run: ./run-test-redis.sh
        working-directory: ./common

      - name: Test & Build internal only
        run: ./gradlew :internal:build

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{ always() }}
        with:
          files: ${{ github.workspace }}/internal/build/test-results/**/*.xml
          seconds_between_github_reads: 1.0
          seconds_between_github_writes: 3.0
          secondary_rate_limit_wait_seconds: 90.0

      - name: When test fail, comment on that code
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: ${{ github.workspace }}/internal/build/test-results/**/*.xml
          token: ${{ github.token }}
